server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.50:5432/inventorytracker
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin123